export const items = [
  {
    id: "M01",
    category: "Men",
    itemname: "T-Shirt 1",
    price: "200",
    imgsrc: "src/images/men/pexels-mart-production-9558233.jpg",
  },
  {
    id: "M02",
    category: "Men",
    itemname: "T-Shirt 2",
    price: "500",
    imgsrc: "src/images/men/product-02-a-400x488.jpg",
  },
  {
    id: "M03",
    category: "Men",
    itemname: "T-Shirt 3",
    price: "350",
    imgsrc: "src/images/men/pexels-mart-production-9558927.jpg",
  },
  {
    id: "M04",
    category: "Men",
    itemname: "T-Shirt 4",
    price: "700",
    imgsrc: "src/images/men/pexels-mwabonje-ringa-1510509.jpg",
  },
  {
    id: "M05",
    category: "Men",
    itemname: "T-Shirt 5",
    price: "1200",
    imgsrc: "src/images/men/pexels-teddy-yang-16131005.jpg",
  },
  {
    id: "F01",
    category: "Women",
    itemname: "T-Shirt 1",
    price: "1000",
    imgsrc: "src/images/front_img.jpg",
  },
  {
    id: "F02",
    category: "Women",
    itemname: "T-Shirt 2",
    price: "200",
    imgsrc: "src/images/women/pexels-mart-production-9558588.jpg",
  },
  {
    id: "F03",
    category: "Women",
    itemname: "T-Shirt 3",
    price: "400",
    imgsrc: "src/images/women/pexels-mart-production-8217291.jpg",
  },
  {
    id: "F04",
    category: "Women",
    itemname: "T-Shirt 4",
    price: "600",
    imgsrc: "src/images/women/pexels-mart-production-9558595.jpg",
  },
  {
    id: "F05",
    category: "Women",
    itemname: "T-Shirt 5",
    price: "500",
    imgsrc: "src/images/women/pexels-mart-production-9558784.jpg",
  },
];
